// ================================================================
// UnitySceneGen — Unity Editor Scene Builder
// Auto-generated by UnitySceneGen tool. Do not edit manually.
// Runs via: -executeMethod UnitySceneGen.Builder.Run
// ================================================================
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace UnitySceneGen
{
    // ── Config models (mirror of orchestrator Core/Models.cs) ─────
    [Serializable]
    public class SceneGenConfig
    {
        [JsonProperty("project")] public ProjectConfig? Project { get; set; }
        [JsonProperty("settings")] public SettingsConfig? Settings { get; set; }
        [JsonProperty("scenes")] public List<SceneConfig> Scenes { get; set; } = new();
        [JsonProperty("gameObjects")] public List<GameObjectConfig> GameObjects { get; set; } = new();
    }
    [Serializable]
    public class ProjectConfig
    {
        [JsonProperty("name")] public string Name { get; set; } = "MyProject";
        [JsonProperty("unityVersion")] public string UnityVersion { get; set; } = "";
        [JsonProperty("packages")] public List<string> Packages { get; set; } = new();
    }
    [Serializable]
    public class SettingsConfig
    {
        [JsonProperty("tags")] public List<string> Tags { get; set; } = new();
        [JsonProperty("layers")] public List<string> Layers { get; set; } = new();
    }
    [Serializable]
    public class SceneConfig
    {
        [JsonProperty("name")] public string Name { get; set; } = "Main";
        [JsonProperty("path")] public string Path { get; set; } = "Assets/Scenes/Main.unity";
        [JsonProperty("roots")] public List<string> Roots { get; set; } = new();
    }
    [Serializable]
    public class GameObjectConfig
    {
        [JsonProperty("id")] public string Id { get; set; } = "";
        [JsonProperty("name")] public string Name { get; set; } = "GameObject";
        [JsonProperty("active")] public bool Active { get; set; } = true;
        [JsonProperty("tag")] public string Tag { get; set; } = "Untagged";
        [JsonProperty("layer")] public string Layer { get; set; } = "Default";
        [JsonProperty("children")] public List<string> Children { get; set; } = new();
        [JsonProperty("components")] public List<ComponentConfig> Components { get; set; } = new();
    }
    [Serializable]
    public class ComponentConfig
    {
        [JsonProperty("type")] public string Type { get; set; } = "";
        [JsonProperty("props")] public JObject? Props { get; set; }
    }
    public class BuilderResult
    {
        [JsonProperty("success")] public bool Success { get; set; }
        [JsonProperty("error")] public string Error { get; set; } = "";
        [JsonProperty("warnings")] public List<string> Warnings { get; set; } = new();
        [JsonProperty("scenes")] public List<string> Scenes { get; set; } = new();
    }

    // ================================================================
    public static class Builder
    {
        private static string ProjectRoot => Directory.GetCurrentDirectory();
        private static string ConfigPath => Path.Combine(ProjectRoot, "SceneGenConfig.json");
        private static string ResultPath => Path.Combine(ProjectRoot, "SceneGenResult.json");
        private static string RunningPath => Path.Combine(ProjectRoot, "SceneGenRunning.json");

        private static readonly Dictionary<string, GameObject> GoMap = new();
        private static readonly Dictionary<string, Component> CompMap = new();
        private static readonly List<string> Warnings = new();

        // ── Entry point ───────────────────────────────────────────────
        public static void Run()
        {
            File.WriteAllText(RunningPath, "{\"running\":true}");
            var result = new BuilderResult();

            try
            {
                Debug.Log("[UnitySceneGen] Builder.Run() started.");

                if (!File.Exists(ConfigPath))
                    throw new FileNotFoundException($"Config not found: {ConfigPath}");

                var cfg = JsonConvert.DeserializeObject<SceneGenConfig>(File.ReadAllText(ConfigPath))
                          ?? throw new Exception("Config deserialized to null.");

                Debug.Log($"[UnitySceneGen] Loaded config: {cfg.Scenes.Count} scene(s), " +
                          $"{cfg.GameObjects.Count} GameObjects.");

                // Step A — ensure tags/layers exist before any GameObject is created
                EnsureTagsAndLayers(cfg);
                AssetDatabase.SaveAssets();
                AssetDatabase.Refresh();

                // Step B — build each scene
                foreach (var sceneConfig in cfg.Scenes)
                {
                    BuildScene(cfg, sceneConfig);
                    result.Scenes.Add(sceneConfig.Path);
                }

                AssetDatabase.SaveAssets();
                AssetDatabase.Refresh();

                result.Success = true;
                result.Warnings = Warnings;
                Debug.Log("[UnitySceneGen] All scenes built successfully.");
            }
            catch (Exception ex)
            {
                result.Success = false;
                result.Error = ex.Message;
                Debug.LogError($"[UnitySceneGen] FATAL: {ex}");
            }
            finally
            {
                File.WriteAllText(ResultPath,
                    JsonConvert.SerializeObject(result, Formatting.Indented));
                if (File.Exists(RunningPath)) File.Delete(RunningPath);
                Debug.Log($"[UnitySceneGen] Result written → {ResultPath}");
            }
        }

        // ── Tags and layers ───────────────────────────────────────────
        private static void EnsureTagsAndLayers(SceneGenConfig cfg)
        {
            if (cfg.Settings == null) return;

            var tagManagerPath = "ProjectSettings/TagManager.asset";
            var assetObj = AssetDatabase.LoadMainAssetAtPath(tagManagerPath);
            if (assetObj == null)
            {
                Warn($"TagManager.asset not found at {tagManagerPath} — tags/layers skipped.");
                return;
            }

            var so = new SerializedObject(assetObj);

            // Tags
            var tagsProp = so.FindProperty("tags");
            if (tagsProp != null)
            {
                foreach (var tag in cfg.Settings.Tags)
                {
                    if (string.IsNullOrEmpty(tag)) continue;
                    bool exists = false;
                    for (int i = 0; i < tagsProp.arraySize; i++)
                        if (tagsProp.GetArrayElementAtIndex(i).stringValue == tag)
                        { exists = true; break; }

                    if (!exists)
                    {
                        tagsProp.arraySize++;
                        tagsProp.GetArrayElementAtIndex(tagsProp.arraySize - 1).stringValue = tag;
                        Debug.Log($"[UnitySceneGen] Added tag: {tag}");
                    }
                }
            }

            // Layers — user slots start at index 8
            var layersProp = so.FindProperty("layers");
            if (layersProp != null)
            {
                foreach (var layer in cfg.Settings.Layers)
                {
                    if (string.IsNullOrEmpty(layer)) continue;
                    bool exists = false;
                    for (int i = 0; i < layersProp.arraySize; i++)
                        if (layersProp.GetArrayElementAtIndex(i).stringValue == layer)
                        { exists = true; break; }

                    if (!exists)
                    {
                        bool placed = false;
                        for (int i = 8; i < layersProp.arraySize; i++)
                        {
                            var elem = layersProp.GetArrayElementAtIndex(i);
                            if (string.IsNullOrEmpty(elem.stringValue))
                            {
                                elem.stringValue = layer;
                                Debug.Log($"[UnitySceneGen] Added layer: {layer} (slot {i})");
                                placed = true;
                                break;
                            }
                        }
                        if (!placed)
                            Warn($"No empty layer slot for '{layer}'. Unity supports max 24 user layers.");
                    }
                }
            }

            so.ApplyModifiedProperties();
        }

        // ── Scene building ────────────────────────────────────────────
        private static void BuildScene(SceneGenConfig cfg, SceneConfig sceneConfig)
        {
            Debug.Log($"[UnitySceneGen] Building scene '{sceneConfig.Name}' → {sceneConfig.Path}");

            GoMap.Clear();
            CompMap.Clear();

            // Ensure output directory exists on disk
            var sceneDir = Path.Combine(ProjectRoot,
                Path.GetDirectoryName(sceneConfig.Path)!.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(sceneDir);

            // Start with a fresh empty scene
            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            var byId = cfg.GameObjects.ToDictionary(g => g.Id);
            var ordered = TopologicalSort(cfg.GameObjects, sceneConfig.Roots, byId);

            // Pass 1 — create bare GameObjects
            foreach (var goCfg in ordered)
                GoMap[goCfg.Id] = CreateGameObject(goCfg);

            // Pass 2 — parent-child relationships
            foreach (var goCfg in ordered)
                foreach (var childId in goCfg.Children)
                    if (GoMap.TryGetValue(childId, out var child) &&
                        GoMap.TryGetValue(goCfg.Id, out var parent))
                        child.transform.SetParent(parent.transform, worldPositionStays: false);

            // Pass 3 — add components in priority order
            foreach (var goCfg in ordered)
                if (GoMap.TryGetValue(goCfg.Id, out var go))
                    AddComponents(go, goCfg);

            // Pass 4 — apply properties (all objects exist, so ref: tokens can resolve)
            foreach (var goCfg in ordered)
                if (GoMap.TryGetValue(goCfg.Id, out var go))
                    ApplyProperties(go, goCfg);

            EditorSceneManager.SaveScene(scene, sceneConfig.Path);
            Debug.Log($"[UnitySceneGen] Scene saved: {sceneConfig.Path}");
        }

        // ── GameObject creation ───────────────────────────────────────
        private static GameObject CreateGameObject(GameObjectConfig cfg)
        {
            var go = new GameObject(cfg.Name);
            go.SetActive(cfg.Active);

            try { go.tag = cfg.Tag; }
            catch
            {
                Warn($"Tag '{cfg.Tag}' not found in TagManager (id={cfg.Id}). " +
                         "Add it to settings.tags in the config.");
            }

            int layer = LayerMask.NameToLayer(cfg.Layer);
            if (layer >= 0) go.layer = layer;
            else Warn($"Layer '{cfg.Layer}' not found (id={cfg.Id}). " +
                      "Add it to settings.layers in the config.");

            Debug.Log($"[UnitySceneGen]   GO '{cfg.Name}' (id={cfg.Id})");
            return go;
        }

        // ── Component ordering ────────────────────────────────────────
        // Canvas must be first so Transform is promoted to RectTransform
        // before any UI child components try to configure it.
        private static int ComponentPriority(string typeName) => typeName switch
        {
            "UnityEngine.Canvas" => 0,
            "UnityEngine.RectTransform" => 1,
            "UnityEngine.UI.CanvasScaler" => 2,
            "UnityEngine.UI.GraphicRaycaster" => 3,
            _ => 10,
        };

        private static void AddComponents(GameObject go, GameObjectConfig goCfg)
        {
            if (goCfg.Components.Count == 0) return;

            var sorted = goCfg.Components
                .OrderBy(c => ComponentPriority(c.Type))
                .ToList();

            foreach (var compCfg in sorted)
            {
                var type = ResolveType(compCfg.Type);
                if (type == null)
                {
                    var msg = $"Type '{compCfg.Type}' not resolved on '{goCfg.Name}'. " +
                              "Verify the type name and that the package is imported.";
                    Debug.LogError($"[UnitySceneGen] {msg}");
                    throw new TypeLoadException(msg);
                }

                Component comp;
                if (type == typeof(Transform))
                {
                    comp = go.transform;
                }
                else if (type == typeof(RectTransform))
                {
                    // May already exist after Canvas was added.
                    // IMPORTANT: use Unity == null, not ??, to detect fake-null returns
                    // from GetComponent when the component does not exist.
                    comp = go.GetComponent<RectTransform>();
                    if (comp == null) comp = go.AddComponent<RectTransform>();
                }
                else
                {
                    // IMPORTANT: use Unity == null check, not ??, because GetComponent
                    // returns a "fake null" (Unity-destroyed object) when not found —
                    // a non-C#-null that fools ?? into skipping AddComponent entirely.
                    comp = go.GetComponent(type);
                    if (comp == null) comp = go.AddComponent(type);
                }

                CompMap[$"{compCfg.Type}:{goCfg.Id}"] = comp;
                Debug.Log($"[UnitySceneGen]     + {compCfg.Type}");
            }
        }

        private static void ApplyProperties(GameObject go, GameObjectConfig goCfg)
        {
            var sorted = goCfg.Components
                .OrderBy(c => ComponentPriority(c.Type))
                .ToList();

            foreach (var compCfg in sorted)
            {
                if (compCfg.Props == null || !compCfg.Props.HasValues) continue;

                var type = ResolveType(compCfg.Type);
                if (type == null) continue;

                var comp = go.GetComponent(type);
                if (comp == null)
                {
                    Warn($"Component {compCfg.Type} not found on '{go.name}' during property apply.");
                    continue;
                }

                foreach (var kv in compCfg.Props)
                    SetMember(comp, kv.Key, kv.Value);
            }
        }

        // ── Reflection member setter ──────────────────────────────────
        private static void SetMember(object target, string memberName, JToken token)
        {
            var type = target.GetType();
            var flags = BindingFlags.Public | BindingFlags.Instance | BindingFlags.IgnoreCase;

            // 1 — public property
            var prop = type.GetProperty(memberName, flags);
            if (prop != null && prop.CanWrite)
            {
                try { prop.SetValue(target, ConvertToken(token, prop.PropertyType)); return; }
                catch (Exception ex) { Warn($"Property '{memberName}' on {type.Name}: {ex.Message}"); return; }
            }

            // 2 — public field
            var field = type.GetField(memberName, flags);
            if (field != null)
            {
                try { field.SetValue(target, ConvertToken(token, field.FieldType)); return; }
                catch (Exception ex) { Warn($"Field '{memberName}' on {type.Name}: {ex.Message}"); return; }
            }

            // 3 — SerializedObject (handles serialized private fields)
            if (target is UnityEngine.Object unityObj)
            {
                var so = new SerializedObject(unityObj);

                // Try exact name then camelCase
                var sp = so.FindProperty(memberName)
                      ?? so.FindProperty(char.ToLower(memberName[0]) + memberName[1..]);

                if (sp != null)
                {
                    SetSerializedProperty(sp, token);
                    so.ApplyModifiedProperties();
                    return;
                }
            }

            Warn($"Member '{memberName}' not found on {type.Name} " +
                 "(checked public property, field, SerializedObject).");
        }

        private static void SetSerializedProperty(SerializedProperty sp, JToken token)
        {
            switch (sp.propertyType)
            {
                case SerializedPropertyType.Boolean: sp.boolValue = token.Value<bool>(); break;
                case SerializedPropertyType.Integer: sp.intValue = token.Value<int>(); break;
                case SerializedPropertyType.Float: sp.floatValue = token.Value<float>(); break;
                case SerializedPropertyType.String: sp.stringValue = token.Value<string>()!; break;
                case SerializedPropertyType.Enum:
                    var idx = Array.IndexOf(sp.enumNames, token.Value<string>());
                    if (idx >= 0) sp.enumValueIndex = idx;
                    else Warn($"Enum value '{token}' not in [{string.Join(", ", sp.enumNames)}]");
                    break;
                case SerializedPropertyType.Color:
                    if (ColorUtility.TryParseHtmlString(token.Value<string>(), out var c))
                        sp.colorValue = c;
                    else Warn($"Cannot parse color: {token}");
                    break;
                case SerializedPropertyType.Vector2:
                    var a2 = token.ToObject<float[]>()!;
                    sp.vector2Value = new Vector2(a2[0], a2[1]);
                    break;
                case SerializedPropertyType.Vector3:
                    var a3 = token.ToObject<float[]>()!;
                    sp.vector3Value = new Vector3(a3[0], a3[1], a3[2]);
                    break;
                case SerializedPropertyType.Vector4:
                    var a4 = token.ToObject<float[]>()!;
                    sp.vector4Value = new Vector4(a4[0], a4[1], a4[2], a4[3]);
                    break;
                default:
                    Warn($"No SerializedProperty handler for {sp.propertyType} ('{sp.name}').");
                    break;
            }
        }

        // ── Token → CLR conversion ────────────────────────────────────
        private static object? ConvertToken(JToken token, Type target)
        {
            var t = Nullable.GetUnderlyingType(target) ?? target;

            if (t == typeof(bool)) return token.Value<bool>();
            if (t == typeof(int)) return token.Value<int>();
            if (t == typeof(float)) return token.Value<float>();
            if (t == typeof(double)) return token.Value<double>();
            if (t == typeof(string)) return token.Value<string>();

            if (t.IsEnum)
                return Enum.Parse(t, token.Value<string>()!, ignoreCase: true);

            if (t == typeof(Color))
            {
                if (ColorUtility.TryParseHtmlString(token.Value<string>(), out var col)) return col;
                Warn($"Cannot parse color '{token}'"); return Color.white;
            }

            if (t == typeof(Vector2)) { var a = token.ToObject<float[]>()!; return new Vector2(a[0], a[1]); }
            if (t == typeof(Vector3)) { var a = token.ToObject<float[]>()!; return new Vector3(a[0], a[1], a[2]); }
            if (t == typeof(Vector4)) { var a = token.ToObject<float[]>()!; return new Vector4(a[0], a[1], a[2], a[3]); }

            // ref:<id> — resolve to a live GameObject or Component
            if (token.Type == JTokenType.String)
            {
                var s = token.Value<string>()!;
                if (s.StartsWith("ref:"))
                {
                    var id = s[4..];
                    if (GoMap.TryGetValue(id, out var go))
                    {
                        if (typeof(GameObject).IsAssignableFrom(t)) return go;
                        if (typeof(Component).IsAssignableFrom(t)) return go.GetComponent(t);
                    }
                    foreach (var kv in CompMap)
                        if (kv.Key.EndsWith($":{id}") && t.IsAssignableFrom(kv.Value.GetType()))
                            return kv.Value;

                    Warn($"ref:'{id}' could not be resolved to type {t.Name}.");
                    return null;
                }
            }

            try { return token.ToObject(t); }
            catch { Warn($"Cannot convert '{token}' to {t.Name}."); return null; }
        }

        // ── Type resolution ───────────────────────────────────────────
        private static readonly string[] KnownAssemblies =
        {
            "UnityEngine",
            "UnityEngine.CoreModule",
            "UnityEngine.UIModule",
            "UnityEngine.UI",
            "UnityEngine.PhysicsModule",
            "UnityEngine.AnimationModule",
            "UnityEngine.AudioModule",
            "Unity.TextMeshPro",
            "UnityEngine.EventSystems",
        };

        private static readonly Dictionary<string, Type> TypeCache = new();

        private static Type? ResolveType(string name)
        {
            if (TypeCache.TryGetValue(name, out var cached)) return cached;

            var t = Type.GetType(name);
            if (t != null) return Cache(name, t);

            foreach (var asm in KnownAssemblies)
            {
                t = Type.GetType($"{name}, {asm}");
                if (t != null) return Cache(name, t);
            }

            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                t = asm.GetType(name, throwOnError: false);
                if (t != null) return Cache(name, t);
            }

            return null;
        }

        private static Type Cache(string name, Type t) { TypeCache[name] = t; return t; }

        // ── Topological sort (parents before children) ────────────────
        private static List<GameObjectConfig> TopologicalSort(
            List<GameObjectConfig> all, List<string> roots,
            Dictionary<string, GameObjectConfig> byId)
        {
            var result = new List<GameObjectConfig>();
            var visited = new HashSet<string>();

            void Visit(string id)
            {
                if (visited.Contains(id)) return;
                visited.Add(id);
                if (!byId.TryGetValue(id, out var go)) return;
                result.Add(go);
                foreach (var child in go.Children) Visit(child);
            }

            foreach (var r in roots) Visit(r);
            // Pick up any objects not reachable from roots
            foreach (var go in all) Visit(go.Id);

            return result;
        }

        // ── Warning helper ────────────────────────────────────────────
        private static void Warn(string msg)
        {
            Warnings.Add(msg);
            Debug.LogWarning($"[UnitySceneGen] WARNING: {msg}");
        }
    }
}